# Generated by Django 5.2.1 on 2025-05-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
