# Generated by Django 5.2 on 2025-05-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReclamos', '0003_alter_comentario_reclamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
    ]
