# Generated by Django 5.2 on 2025-05-27 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppReclamos', '0004_reclamo_comprobante'),
        ('AppReclamos', '0004_reclamo_evidencia'),
    ]

    operations = [
    ]
